services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: sghss
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - sghss:/var/lib/mysql

volumes:
  sghss:
